version: '3.1'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - 5000:5000
    environment:
      API_PORT: 5000
      JWT_SECRET: eShVmYq3t6w9z$C&F)J@NcQfTjWnZr4u
      MONGO_USER: mongo
      MONGO_PASS: mongo_password
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
